help for pySC.core.simulated_commissioning.register_bpms
lmalina/pySC pull request #32
Opened 2023-08-01 14:01 UTC by simoneliuzzo

copy of help from **SCregisterBPMs**

2023-08-02 10:42 UTC, simoneliuzzo commented
Dear @lmalina 

let me know if it is ok for you. 

any comment is welcome.

best regards
@simoneliuzzo

2023-08-02 11:52 UTC, lmalina reviewed
Dear Simone,

thank you for your contribution, here I put some general comments:
Often the docstring still reflect the Matlab code, especially in the examples 

- Matlab syntax (semicolons in the end of line,types of brackets, ...)
- SC structure passed as an argument and returned
- the see also functions are sometimes the matlab ones

When referering to the data structures where the registered indices are stored I would point to  corresponding classes in `core.classes`, potentially in conection to that document the `SimulatedCommissioning.__init__`

When reading the docstrings, I am wondering if the allowed kwargs in register functions should be made more uniform and describe them a bit more globally.

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +    SC.applyErrors functions apply those sigmas to specific elements in the lattice
`apply_errors` function

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +    SC.update transfer the information to the AT elements fields
update functions

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +        """registers BPMs specified by the locations `BPMords` in the `SC` structure and initializes all required fields
specified by `ords` (element indices in the lattice)

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                Calibration error of the sum signal. The sum signal is used to determine the beam loss location with a cutoff as defined `SC.INJ.beamLostAt`.
No support-related kwargs and the arrays are single dimension

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                SC = SC.register_bpms(SC, ords, Offset=500E-6*[1, 1]);
Offset is numpy array

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +            *SCgetBPMreading*, *SCgetOrds*, *SC.sanity_check*, *SC.apply_errors*, *SC.register_support*, *SC.update_support*
`core.beam.bpr_reading`, ..., `verify_structure`...

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +        """Register cavities specified in `CAVords` in `SC` by initializing all required fields in the
`ords`

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +        corresponding cavity lattice elements and storing the ordinates in `SC.ORD.Cavity`.
`SC.ORD.RF`

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +            to 1kHz. A subsequent call of *SCapplyErrors* would generate a random frequncy offset error with `sigma=1kHz`::
`apply_errors`

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                SC = SC.register_cavities(SC,ords);
`SC.register_cavities(ords)`

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                SC = SC.register_bpms(SC,ords, Offset=500E-6*[1, 1], SumError=0.2);
`SC.register_bpms(ords, Offset=500E-6*np.ones(2), SumError=0.2)

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                currently not be updated correctly.
These are not the fields of lattice elements.

2023-08-02 11:52 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +            BA: [N x 2] array of PolynomA/B multipole errors.
PolynomB/A

2023-08-02 13:07 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                Calibration error of the sum signal. The sum signal is used to determine the beam loss location with a cutoff as defined `SC.INJ.beamLostAt`.
and how do you specify horizontal and vertical?

2023-08-02 13:12 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                SC = SC.register_bpms(SC, ords, Offset=500E-6*[1, 1]);
Dear @lmalina,
then it would become  `SC = SC.register_bpms(SC, ords, Offset=numpy.array(500E-6*[1, 1]));`
or is there a nicer to see way to do it?

2023-09-12 07:21 UTC, simoneliuzzo commented
Dear @lmalina and @linahv,

today I will work on this project. 

Let me know if you want to meet on zoom. 

ciao
simone

2023-09-12 07:44 UTC, simoneliuzzo commented
Dear @lmalina, @ThorstenHellert ,

in `register_magnets` `CalErrorB` is a 1D array of 2 elements. In the help it seems it is supposed to be a scalar. What are the two elements for (I could go read the code, but may be you know the answer stragiht away)

2023-09-12 08:28 UTC, lmalina commented
> Dear @lmalina, @ThorstenHellert ,
> 
> in `register_magnets` `CalErrorB` is a 1D array of 2 elements. In the help it seems it is supposed to be a scalar. What are the two elements for (I could go read the code, but may be you know the answer stragiht away)

It may have an arbitrary number of elements, similar to `PolynomB`.

2023-09-12 08:31 UTC, simoneliuzzo commented
Dear @lmalina,

what is the tracking mode `PORB`?

2023-09-12 08:35 UTC, lmalina commented
> Dear @lmalina,
> 
> what is the tracking mode `PORB`?

It is turn-by-turn tracking with trajectories averaged over the turns,  i.e. pseudo closed orbit.

2023-09-12 09:00 UTC, simoneliuzzo commented
Dear @lmalina and @ThorstenHellert ,

I have come across `switch_cavity_and_radiation`

There are AT methods for this.

I will propose a separate pull request for this purpose

2023-09-12 09:06 UTC, lmalina commented
> Dear @lmalina and @ThorstenHellert ,
> 
> I have come across `switch_cavity_and_radiation`
> 
> There are AT methods for this.
> 
> I will propose a separate pull request for this purpose

Good! We need to evaluate if this method is still needed. In practice, I use a combination of enable/disable_6d from pyAT and `switch_rf`.

2023-09-13 10:54 UTC, lmalina requested changes
Thank you! I have not gone through all the code, however I hope the comments I made are understandable even though short. I think the documentation can profit from better "alignment" with the code, it is already quite close. 
 
In general, I think we should profit from things that are hard to document to improve the code.

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +    using other means than linear algebra.  In this approach the kicks of an
I would clarify and rephrase this.

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +    response matrix to the two-turn BPM data.
Trajectory at first BPMs in the second turn is corrected to their first-turn trajectory?

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +        three BPMs, a maximum of 20 steps and print debug information::
no debug print

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +            SC.INJ.nTurns = 2
twice

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +    and/or BPM ordinates for the correction is explicitly given (see options below). `SC.RING` is
I would write that for the moment no filtering is included and shapes have to match

2023-09-13 10:54 UTC, lmalina commented on pySC/correction/orbit_trajectory.py
> +    also return, if transmission is lost.
It raises `RuntimeError`

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +    horizontal and vertical CMs respectively.
If `useIdealRing=False`

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +            The idealised RING structure, which was used to determine the RM.
Not returned

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +    Determine the lattice response matrix based on current setpoints.
Merge in a single description

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +    errors. Optionally the design lattice is used.
Also here, I would think, it should be a single description

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +    lattice errors and dipole fields are excluded.
Merge

2023-09-13 10:54 UTC, lmalina commented on pySC/lattice_properties/response_model.py
> +        SC: SimulatedCommissioning class instance
Very nice!

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +            This parameter is set via *SC.register_magnets*, *SC.register_bpms*, *SC.register_cavities*
I guess no `SC` and also `register_supports`

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +            This parameter is set via *SC.register_magnets*, *SC.register_bpms*, *SC.register_cavities*
same as above

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +        """registers BPMs specified by the locations `ords` (element indices in the lattice) in the `SC` structure and
no locations, and `SImulatedCommissioning` class

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                2 elements array of hor./ver. BPM offsets which result from the corresponding girder offset at the location of the BPMs, see *SCupdateSupport*.
I find this a bit confusing, it cannot be set here

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                BPM roll around z-axis which results from the corresponding support structure roll at the location of the BPMs, see *SCupdateSupport*.
same as `SupportOffset`

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                SC.register_bpms(ords, Offset=[500E-6*np.ones(2), 3])
This is still possible to do. However, I would try a more elegant way to do it. I am not sure if to show this example.

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +
I wonder what the `Setpoint`s actually do

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                Setpoints for the `PolynomA` fields.
Not keywords

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                Each element of the numpy.array is the error for the corresponding element in 'PolynomA'
not keywords here (at least for the moment) belongs to multipole errors

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                registered).
not here ... `register_supports`

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +                around y-axis); all wrt. the design coordinate frame (if support structure is registered).
not here

2023-09-13 10:54 UTC, lmalina commented on pySC/core/simulated_commissioning.py
> +
All the rest is also optional

2023-09-15 04:23 UTC, simoneliuzzo commented on pySC/core/classes.py
> +             (default=numpy.zeros((6,6)))  Injected beam random trajectory jitter
ok

2023-09-15 04:24 UTC, simoneliuzzo commented on pySC/core/classes.py
> +    properties of this class are:
ok

2023-09-15 04:24 UTC, simoneliuzzo commented on pySC/core/classes.py
> +            (default=numpy.zeros(6)) Injetced trajectory
ok

2023-09-15 04:26 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +    Reads the setpoints of the CMs specified in `ords` in the dimension `skewness`.
ok

2023-09-15 04:26 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +        The list of acutal setpoints applied to the magnets after possible clipping [rad]
ok

2023-09-15 04:32 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +    field `SkewQuadLimit`, the setpoint is clipped to that value and a warning is being printed (to
Where is SkewQuadLimit found then? SC.??.SkewQuadLimit

2023-09-15 04:43 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +        setpoints:  CM setpoints (array or single value for all CMs) [rad]
not clear to me. I undestood that setpoints as an array would be assigned to all corresponding values in PolynmoB/A (according to skewness). 
For example: setpoints = [0.1,0.2,0.3], skewness=False, method 'rel', then PolynomB[0,1,2] = PolynomB[0,1,2]  + [0.1,0.2,0.3]

2023-09-15 04:46 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +                'rel', Use relative setpoint to current value
ok. I modified it also for cavities.

2023-09-15 04:48 UTC, simoneliuzzo commented on pySC/core/lattice_setting.py
> +                                      method='abs')
I have added `SC.register_magnets(ords)`

2023-09-15 04:51 UTC, simoneliuzzo commented on pySC/correction/orbit_trajectory.py
> +    achieves one-turn transmission
not clear to me how to modify

2023-09-15 04:52 UTC, simoneliuzzo commented on pySC/correction/orbit_trajectory.py
> +    using other means than linear algebra.  In this approach the kicks of an
may be it is needed, but this is how it is explained in SC

2023-09-15 04:53 UTC, simoneliuzzo commented on pySC/correction/orbit_trajectory.py
> +    response matrix to the two-turn BPM data.
yes, this makes sense, to go from open trajectory to closed the orbit

2023-09-15 08:27 UTC, simoneliuzzo commented on pySC/correction/orbit_trajectory.py
> +    and/or BPM ordinates for the correction is explicitly given (see options below). `SC.RING` is
for me this is obvious and clear from the help. I do not know what you intend for filtering. I will change CM[0] to HCM

2023-09-15 08:32 UTC, simoneliuzzo commented on pySC/lattice_properties/response_model.py
> +    horizontal and vertical CMs respectively.
I have added this in the Args description

2023-09-15 08:35 UTC, simoneliuzzo commented on pySC/lattice_properties/response_model.py
> +    Determine the lattice response matrix based on current setpoints.
It is done like this everywhere. It is a bit matlab style but I do find it nice. First a one sentence summary, then further explaination.

2023-09-15 08:35 UTC, simoneliuzzo commented on pySC/lattice_properties/response_model.py
> +    errors. Optionally the design lattice is used.
same as above

2023-09-15 08:35 UTC, simoneliuzzo commented on pySC/lattice_properties/response_model.py
> +    lattice errors and dipole fields are excluded.
same as above

2023-09-15 08:50 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                2 elements array of hor./ver. BPM offsets which result from the corresponding girder offset at the location of the BPMs, see *SCupdateSupport*.
I added it cause I saw it in the code below. there it is set to zero infact. This means that register_bpms has to be called always before any register_support?

2023-09-15 08:53 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                2 elements array of hor./ver. BPM offsets which result from the corresponding girder offset at the location of the BPMs, see *SCupdateSupport*.
I think I understand now. The fields are initialized to zero in the SC.RING structure. apply_errors will set them later.

2023-09-15 08:55 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                SC.register_bpms(ords, Offset=[500E-6*np.ones(2), 3])
Is there a better input? I would have put the cut off as a separate keyword argument default to 2.5 as in all litterature...

2023-09-15 08:57 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +
I do not understand your comment. For me this is quite clear. if you want to set RF voltage to 6MV, either you do VoltageSetPoint=6.0  and VoltageOffset=0.0 (what are the units here??) or viceversa, or any intermediate combination.

2023-09-15 08:59 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                Setpoints for the `PolynomA` fields.
ok. Yet, where to find the correct keywords list?

2023-09-15 09:00 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +                registered).
ok, but still, I do not understand from the code, what is to be kept and what is not.

2023-09-15 09:01 UTC, simoneliuzzo commented on pySC/core/simulated_commissioning.py
> +
I remove the (optional)

2023-09-26 08:30 UTC, lmalina approved these changes
Thank you Simone, let's merge this!

2023-09-26 08:31 UTC, simoneliuzzo commented
great!

2023-09-26 08:33 UTC, merged